sudo: requried
language: node_js
node_js:
  - 'node'
  - 'lts/*'

services:
  - docker

before_install:
  - docker build -t rimaig/react-app -f Dockerfile.dev .

script:
  - docker run rimaig/react-app npm run test -- --coverage
