sudo: requried
language: node_js
node_js:
  - 'node'
  - 'lts/*'

services:
  - docker

before_install:
  - docker build -t rimaig/react-app -f Dockerfile.dev .

script:
  - docker run rimaig/react-app yarn test --coverage .

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-510645718273"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  
 