sudo: requried
language: node_js
node_js:
  - 'node'
  - 'lts/*'

services:
  - docker

before_install:
  - docker build -t rimaig/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true rimaig/react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-test"
  env: Reacttest-env"
  bucket_name: "elasticbeanstalk-us-east-1-510645718273"
  bucket_path: "react-test"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  
 